AWSTemplateFormatVersion: 2010-09-09
#######################################################################################################################################################
# Description: The template creates an Ec2 instance in the subnet, AZ of your choice and with Key, Sec group, Name, Type that you choose in parameters
#
# Stack History:
# Version       Date            Created by             Summary
# -------       -----------     ------------------      -------------------------------------------------------
# 1.0           17-May-2022     Ankit Pant           Baseline template
######################################################################################################################################################
Description: The template creates an Ec2 instance.

Parameters: 
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Enter the id of the subnet where ypu want to create the instance
  AmiId:
    Type: String
    Description: Enter the AWS AMI id
  InstanceType:
    Type: String
    Description: Enter the instance type e.g t2.micro, m1.small
    Default: t2.micro
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: enter the AZ where you want to create your instance
  Ec2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Enter an existing key pair
  InstanceName:
    Type: String
    Description: Enter a name for your instance
    MinLength: 3
    MaxLength: 10
  SecGroup: 
    Type: AWS::EC2::SecurityGroup::Id
  
Resources:
  Ec2Instace:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref Ec2KeyPair
      SecurityGroupIds: 
        - !Ref SecGroup
      SubnetId: !Ref SubnetId